### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by ooxi** [less/less-plugin-npm-import#5]
Hi,

the [README.md](https://github.com/less/less-plugin-npm-import/blob/master/README.md#testing) tells me to execute `node test/index.js` but the following exception occurs

```
LESS - npm import


fs.js:659
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'test/less-bom/npm-import/'
    at Object.fs.readdirSync (fs.js:659:18)
    at runTestSetInternal (/home/vk/code/js/less-plugin-npm-import/node_modules/less/test/less-test.js:177:12)
    at Object.runTestSet (/home/vk/code/js/less-plugin-npm-import/node_modules/less/test/less-test.js:159:9)
    at Object.<anonymous> (/home/vk/code/js/less-plugin-npm-import/test/index.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

I think the sentence *"You require the dev dependencies and less v2 in your node_modules (it will be added as a dev dependency once less v2 is released)"* is the answer but I don't know what that means.

**Comment by lukeapage** [comment]
Ah its an incompatibility with the latest less. Install 2.2 to node modules
(npm install less@2.2) and try again. Will put on list on fix.

**Comment by lukeapage** [comment]
dependencies fixed and underlying issue fixed in less, just awaiting release.

**Comment by ooxi** [comment]
Tests are now executed without errors :)
